name: Build and Deploy to Google Cloud Run
on:
  workflow_run:
    workflows:
      - CI Pipeline
    types:
      - completed
permissions:
  id-token: write
  contents: read
  packages: write
jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}
      
      - name: Build and Push to GHCR
        run: |
          GHCR_IMAGE=ghcr.io/${{ github.repository_owner }}/note-api:${{ github.sha }}
          docker build -t $GHCR_IMAGE .
          echo "Pushing to GitHub Container Registry..."
          docker push $GHCR_IMAGE
      
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/70756149774/locations/global/workloadIdentityPools/github-actions/providers/github-repos'
          service_account: 'hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com'
      
      - name: Authenticate Docker with Google Artifact Registry
        run: |
          gcloud auth configure-docker europe-west3-docker.pkg.dev
      
      - name: Copy Image to Google Artifact Registry
        run: |
          GHCR_IMAGE=ghcr.io/${{ github.repository_owner }}/note-api:${{ github.sha }}
          GOOGLE_IMAGE=europe-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/note-api/note-api:${{ github.sha }}
          
          echo "Pulling image from GHCR..."          
          docker pull $GHCR_IMAGE
          echo "Tagging image for GAR..."          
          docker tag $GHCR_IMAGE $GOOGLE_IMAGE
          echo "Pushing image to Google Artifact Registry..."
          docker push $GOOGLE_IMAGE
      
      - name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'note-api-hs-heilbronn-devsecops-teamp123'
          image: 'europe-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/note-api/note-api:${{ github.sha }}'
          region: 'europe-west3'
          env_vars: |
            BACKEND=memory
            GOOGLE_CLOUD_PROJECT=${{ secrets.GCP_PROJECT_ID }}
            OTEL_PYTHON_LOG_CORRELATION=true
            OTEL_SERVICE_NAME=notes-api
            OTEL_TRACES_SAMPLER=always_on
            OTEL_TRACES_EXPORTER=cloud_trace
          project_id: ${{ secrets.GCP_PROJECT_ID }}
