name: CI Pipeline

# This workflow is triggered on pull requests (or pushes to the main branch)
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner environment

    strategy:
      max-parallel: 1  # Limit to 1 parallel job, but tests will run on multiple CPUs

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python (choose the appropriate version)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version (e.g., 3.8, 3.9)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt && pip install -r requirements-dev.txt

      # Step 4: Run tests with pytest, parallelization, and coverage
      - name: Run pytest with coverage
        run: |
          pytest --maxfail=1 --durations=10 -n auto --cov=. --cov-report=xml

      # Optional Step 5: Upload test coverage results to Coveralls or Codecov
      # Uncomment this section if using a coverage service like Coveralls or Codecov
      # - name: Upload coverage to Coveralls (optional)
      #   uses: coverallsapp/github-action@v2
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     path-to-lcov: ./coverage.xml  # Adjust this path if necessary

      # - name: Upload coverage to Codecov (optional)
      #   uses: codecov/codecov-action@v2
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ./coverage.xml
