name: Deploy to Google Cloud Run

on:
  workflow_run:
    workflows:
      - CI Pipeline # Triggers after ci.yaml completes
    types:
      - completed

# Define the permissions for the token
permissions:
  id-token: write  # Allows GitHub Actions to generate ID tokens for authentication
  contents: read   # Allows GitHub Actions to read the repository contents

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/70756149774/locations/global/workloadIdentityPools/github-actions/providers/github-repos'
          service_account: 'hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com'

      # Step 2: Deploy to Google Cloud Run
      - name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: 'note-api-hs-heilbronn-devsecops-teamp123' # Replace <your organisation> with your specific organization name
          image: 'gcr.io/hs-heilbronn-devsecops/note-api:latest' # Use the prebuilt image from your registry
          region: 'us-central1' # Adjust the region as needed
          env_vars: BACKEND=memory
